# Generated by Django 5.0.2 on 2024-04-23 09:02

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("myapi", "0002_alter_user_id"),
    ]

    operations = [
        migrations.AlterField(
            model_name="user",
            name="id",
            field=models.AutoField(db_column="id", primary_key=True, serialize=False),
        ),
    ]
